name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
      # 计划任务语法的五个字段，分别为分钟，小时，每月的第几天，月份，周几  
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Shanghai Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: 13771534326@163.com
          from: GitHub Actions
          content_type: text/html
